// src/app/register/page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";

const schema = z
  .object({
    fullName: z.string().min(2, "Name must be at least 2 characters"),
    email: z.string().email("Please enter a valid email address"),
    phone: z.string().min(8, "Please enter a valid phone number"),
    password: z.string().min(6, "Password must be at least 6 characters"),
    confirmPassword: z.string().min(6),
  })
  .refine((v) => v.password === v.confirmPassword, {
    message: "Passwords do not match",
    path: ["confirmPassword"],
  });

type FormValues = z.infer<typeof schema>;

export default function CustomerRegisterPage() {
  const router = useRouter();
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({ resolver: zodResolver(schema) });

  const onSubmit = async () => {
    await new Promise((r) => setTimeout(r, 700));
    router.push("/login");
  };

  return (
    <section className="mx-auto mt-10 max-w-2xl px-4 sm:px-6">
      <div className="card">
        <h1 className="text-2xl font-bold text-slate-900">Customer Registration</h1>
        <p className="mt-1 text-sm text-slate-600">Create your customer account.</p>

        <form className="mt-6 grid gap-4 md:grid-cols-2" onSubmit={handleSubmit(onSubmit)}>
          <div>
            <label className="mb-1 block text-sm font-semibold">Full Name</label>
            <input className="field" {...register("fullName")} />
            {errors.fullName ? <p className="mt-1 text-xs text-red-600">{errors.fullName.message}</p> : null}
          </div>
          <div>
            <label className="mb-1 block text-sm font-semibold">Email Address</label>
            <input className="field" type="email" {...register("email")} />
            {errors.email ? <p className="mt-1 text-xs text-red-600">{errors.email.message}</p> : null}
          </div>
          <div>
            <label className="mb-1 block text-sm font-semibold">Phone Number</label>
            <input className="field" {...register("phone")} />
            {errors.phone ? <p className="mt-1 text-xs text-red-600">{errors.phone.message}</p> : null}
          </div>
          <div>
            <label className="mb-1 block text-sm font-semibold">Password</label>
            <input className="field" type="password" {...register("password")} />
            {errors.password ? <p className="mt-1 text-xs text-red-600">{errors.password.message}</p> : null}
          </div>
          <div className="md:col-span-2">
            <label className="mb-1 block text-sm font-semibold">Confirm Password</label>
            <input className="field" type="password" {...register("confirmPassword")} />
            {errors.confirmPassword ? (
              <p className="mt-1 text-xs text-red-600">{errors.confirmPassword.message}</p>
            ) : null}
          </div>
          <div className="md:col-span-2">
            <button className="btn btn-primary w-full" disabled={isSubmitting} type="submit">
              {isSubmitting ? "Creating account..." : "Register as Customer"}
            </button>
          </div>
        </form>

        <div className="mt-4 text-center text-sm">
          <Link href="/login" className="text-brand hover:underline">
            Already have account? Sign in
          </Link>
        </div>
      </div>
    </section>
  );
}

// src/app/components/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup;
  isLoading = false;
  showPassword = false;
  showConfirmPassword = false;

  constructor(
    private fb: FormBuilder,
    private router: Router
  ) {
    this.registerForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.required, Validators.pattern(/^[0-9+\-\s()]+$/)]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]],
      agreeToTerms: [false, [Validators.requiredTrue]]
    }, { validators: this.passwordMatchValidator });
  }

  ngOnInit(): void {
    // Demo registration form
  }

  passwordMatchValidator(form: FormGroup) {
    const password = form.get('password');
    const confirmPassword = form.get('confirmPassword');
    
    if (password && confirmPassword && password.value !== confirmPassword.value) {
      confirmPassword.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    
    return null;
  }

  onSubmit(): void {
    if (this.registerForm.valid) {
      this.isLoading = true;
      const { name, email, phone, password } = this.registerForm.value;

      // Mock registration - in real app, this would call auth service
      setTimeout(() => {
        this.isLoading = false;
        alert('Registration successful! (This is a demo)');
        this.router.navigate(['/']);
      }, 1000);
    } else {
      this.markFormGroupTouched();
    }
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword = !this.showConfirmPassword;
  }

  private markFormGroupTouched(): void {
    Object.keys(this.registerForm.controls).forEach(key => {
      const control = this.registerForm.get(key);
      control?.markAsTouched();
    });
  }

  getFieldError(fieldName: string): string {
    const field = this.registerForm.get(fieldName);
    if (field?.errors && field.touched) {
      if (field.errors['required']) {
        return `${fieldName.charAt(0).toUpperCase() + fieldName.slice(1)} is required`;
      }
      if (field.errors['email']) {
        return 'Please enter a valid email address';
      }
      if (field.errors['minlength']) {
        if (fieldName === 'name') {
          return 'Name must be at least 2 characters long';
        }
        return 'Password must be at least 6 characters long';
      }
      if (field.errors['pattern']) {
        return 'Please enter a valid phone number';
      }
      if (field.errors['passwordMismatch']) {
        return 'Passwords do not match';
      }
      if (field.errors['requiredTrue']) {
        return 'You must agree to the terms and conditions';
      }
    }
    return '';
  }
}

<div class="auth-page">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 col-lg-6">
        <div class="card shadow-lg border-0">
          <div class="card-body p-5">
            <div class="text-center mb-4">
              <h2 class="fw-bold text-primary">
                <i class="fa fa-users me-2"></i>Customer Registration
              </h2>
              <p class="text-muted">Join MaidFinder and find your perfect domestic helper</p>
            </div>

            <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
              <div class="row">
                <!-- Name Field -->
                <div class="col-md-6 mb-3">
                  <label for="name" class="form-label">Full Name</label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-user"></i>
                    </span>
                    <input
                      type="text"
                      id="name"
                      formControlName="name"
                      class="form-control"
                      [class.is-invalid]="getFieldError('name')"
                      placeholder="Enter your full name">
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('name')">
                    {{ getFieldError('name') }}
                  </div>
                </div>

                <!-- Email Field -->
                <div class="col-md-6 mb-3">
                  <label for="email" class="form-label">Email Address</label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-envelope"></i>
                    </span>
                    <input
                      type="email"
                      id="email"
                      formControlName="email"
                      class="form-control"
                      [class.is-invalid]="getFieldError('email')"
                      placeholder="Enter your email">
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('email')">
                    {{ getFieldError('email') }}
                  </div>
                </div>
              </div>

              <div class="row">
                <!-- Phone Field -->
                <div class="col-md-6 mb-3">
                  <label for="phone" class="form-label">Phone Number</label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-phone"></i>
                    </span>
                    <input
                      type="tel"
                      id="phone"
                      formControlName="phone"
                      class="form-control"
                      [class.is-invalid]="getFieldError('phone')"
                      placeholder="Enter your phone number">
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('phone')">
                    {{ getFieldError('phone') }}
                  </div>
                </div>
              </div>

              <div class="row">
                <!-- Password Field -->
                <div class="col-md-6 mb-3">
                  <label for="password" class="form-label">Password</label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-lock"></i>
                    </span>
                    <input
                      [type]="showPassword ? 'text' : 'password'"
                      id="password"
                      formControlName="password"
                      class="form-control"
                      [class.is-invalid]="getFieldError('password')"
                      placeholder="Create a password">
                    <button
                      type="button"
                      class="btn btn-outline-secondary"
                      (click)="togglePasswordVisibility()">
                      <i class="fa" [class.fa-eye]="!showPassword" [class.fa-eye-slash]="showPassword"></i>
                    </button>
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('password')">
                    {{ getFieldError('password') }}
                  </div>
                </div>

                <!-- Confirm Password Field -->
                <div class="col-md-6 mb-3">
                  <label for="confirmPassword" class="form-label">Confirm Password</label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-lock"></i>
                    </span>
                    <input
                      [type]="showConfirmPassword ? 'text' : 'password'"
                      id="confirmPassword"
                      formControlName="confirmPassword"
                      class="form-control"
                      [class.is-invalid]="getFieldError('confirmPassword')"
                      placeholder="Confirm your password">
                    <button
                      type="button"
                      class="btn btn-outline-secondary"
                      (click)="toggleConfirmPasswordVisibility()">
                      <i class="fa" [class.fa-eye]="!showConfirmPassword" [class.fa-eye-slash]="showConfirmPassword"></i>
                    </button>
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('confirmPassword')">
                    {{ getFieldError('confirmPassword') }}
                  </div>
                </div>
              </div>

              <!-- Terms and Conditions -->
              <div class="mb-4">
                <div class="form-check">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    id="agreeToTerms"
                    formControlName="agreeToTerms"
                    [class.is-invalid]="getFieldError('agreeToTerms')">
                  <label class="form-check-label" for="agreeToTerms">
                    I agree to the
                    <a href="#" class="text-decoration-none">Terms of Service</a>
                    and
                    <a href="#" class="text-decoration-none">Privacy Policy</a>
                  </label>
                </div>
                <div class="invalid-feedback d-block" *ngIf="getFieldError('agreeToTerms')">
                  {{ getFieldError('agreeToTerms') }}
                </div>
              </div>

              <!-- Submit Button -->
              <button
                type="submit"
                class="btn btn-primary w-100 py-2 mb-3"
                [disabled]="isLoading">
                <span *ngIf="isLoading" class="spinner-border spinner-border-sm me-2"></span>
                <i class="fa fa-user-plus me-2" *ngIf="!isLoading"></i>
                {{ isLoading ? 'Creating Account...' : 'Register as Customer' }}
              </button>
            </form>

            <!-- Divider -->
            <div class="text-center my-4">
              <span class="text-muted">Already have a customer account?</span>
            </div>

            <!-- Login Link -->
            <div class="text-center mb-3">
              <a routerLink="/login" class="btn btn-outline-primary w-100">
                <i class="fa fa-sign-in me-2"></i>Sign In Instead
              </a>
            </div>

            <!-- Switch to Maid Registration -->
            <div class="text-center">
              <a routerLink="/maid-register" class="text-decoration-none text-muted small">
                <i class="fa fa-user-circle me-1"></i>Are you a Maid? Register here
              </a>
            </div>
          </div>
        </div>

        <!-- Additional Info -->
        <div class="text-center mt-4">
          <p class="text-muted small">
            By creating an account, you agree to our
            <a href="#" class="text-decoration-none">Terms of Service</a>
            and
            <a href="#" class="text-decoration-none">Privacy Policy</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
