// src/app/components/auth/maid-register/maid-register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-maid-register',
  templateUrl: './maid-register.component.html',
  styleUrls: ['./maid-register.component.scss']
})
export class MaidRegisterComponent implements OnInit {
  maidRegisterForm: FormGroup;
  isLoading = false;
  showPassword = false;
  showConfirmPassword = false;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private router: Router
  ) {
    this.maidRegisterForm = this.fb.group({
      fullName: ['', [Validators.required, Validators.minLength(2)]],
      gender: ['', [Validators.required]],
      nationality: ['', [Validators.required, Validators.minLength(2)]],
      emirate: ['', [Validators.required]],
      visaStatus: ['', [Validators.required]],
      visaExpiryDate: ['', [Validators.required]],
      mobileNumber: ['', [Validators.required, Validators.pattern(/^[0-9]{9}$/)]],
      whatsappEmirate: ['4', [Validators.required]], // Default Dubai
      whatsappNumber: ['', [Validators.required, Validators.pattern(/^[0-9]{7}$/)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]],
      agreeToTerms: [false, [Validators.requiredTrue]]
    }, { validators: this.passwordMatchValidator });
  }

  ngOnInit(): void {
    // Set minimum date to today for visa expiry
    const today = new Date().toISOString().split('T')[0];
    const visaExpiryInput = document.getElementById('visaExpiryDate') as HTMLInputElement;
    if (visaExpiryInput) {
      visaExpiryInput.setAttribute('min', today);
    }
  }

  passwordMatchValidator(form: FormGroup) {
    const password = form.get('password');
    const confirmPassword = form.get('confirmPassword');
    
    if (password && confirmPassword && password.value !== confirmPassword.value) {
      confirmPassword.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    
    return null;
  }

  onSubmit(): void {
    if (this.maidRegisterForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';

      const formValue = this.maidRegisterForm.value;
      
      // Format mobile number with country code
      const mobileNumber = `+971${formValue.mobileNumber}`;
      
      // Format WhatsApp number
      const whatsappNumber = `+971${formValue.whatsappEmirate}${formValue.whatsappNumber}`;

      const maidData = {
        fullName: formValue.fullName,
        gender: formValue.gender,
        nationality: formValue.nationality,
        emirate: formValue.emirate,
        visaStatus: formValue.visaStatus,
        visaExpiryDate: formValue.visaExpiryDate,
        mobileNumber: mobileNumber,
        whatsappNumber: whatsappNumber,
        email: formValue.email,
        password: formValue.password,
        role: 'maid'
      };

      // Mock registration - in real app, this would call auth service
      setTimeout(() => {
        this.isLoading = false;
        console.log('Maid Registration Data:', maidData);
        alert('Registration successful! Your profile is being created. (This is a demo)');
        this.router.navigate(['/login']);
      }, 1500);
    } else {
      this.markFormGroupTouched();
      this.errorMessage = 'Please fill in all required fields correctly.';
    }
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword = !this.showConfirmPassword;
  }

  private markFormGroupTouched(): void {
    Object.keys(this.maidRegisterForm.controls).forEach(key => {
      const control = this.maidRegisterForm.get(key);
      control?.markAsTouched();
    });
  }

  formatMobileNumber(event: any): void {
    let value = event.target.value.replace(/\D/g, '');
    if (value.length > 9) {
      value = value.substring(0, 9);
    }
    this.maidRegisterForm.patchValue({ mobileNumber: value }, { emitEvent: false });
  }

  formatWhatsAppNumber(event: any): void {
    let value = event.target.value.replace(/\D/g, '');
    if (value.length > 7) {
      value = value.substring(0, 7);
    }
    this.maidRegisterForm.patchValue({ whatsappNumber: value }, { emitEvent: false });
  }

  getFieldError(fieldName: string): string {
    const field = this.maidRegisterForm.get(fieldName);
    if (field?.errors && field.touched) {
      if (field.errors['required']) {
        return `${this.getFieldLabel(fieldName)} is required`;
      }
      if (field.errors['email']) {
        return 'Please enter a valid email address';
      }
      if (field.errors['minlength']) {
        if (fieldName === 'fullName' || fieldName === 'nationality') {
          return `${this.getFieldLabel(fieldName)} must be at least 2 characters long`;
        }
        return 'Password must be at least 6 characters long';
      }
      if (field.errors['pattern']) {
        if (fieldName === 'mobileNumber') {
          return 'Mobile number must be 9 digits';
        }
        if (fieldName === 'whatsappNumber') {
          return 'WhatsApp number must be 7 digits';
        }
        return 'Please enter a valid number';
      }
      if (field.errors['passwordMismatch']) {
        return 'Passwords do not match';
      }
      if (field.errors['requiredTrue']) {
        return 'You must agree to the terms and conditions';
      }
    }
    return '';
  }

  private getFieldLabel(fieldName: string): string {
    const labels: { [key: string]: string } = {
      fullName: 'Full Name',
      gender: 'Gender',
      nationality: 'Nationality',
      emirate: 'Emirate',
      visaStatus: 'Visa Status',
      visaExpiryDate: 'Visa Expiry Date',
      mobileNumber: 'Mobile Number',
      whatsappNumber: 'WhatsApp Number',
      email: 'Email Address',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      agreeToTerms: 'Terms and Conditions'
    };
    return labels[fieldName] || fieldName;
  }
}

<div class="auth-page">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10 col-lg-8">
        <div class="card shadow-lg border-0">
          <div class="card-body p-5">
            <div class="text-center mb-4">
              <h2 class="fw-bold text-primary">
                <i class="fa fa-user-plus me-2"></i>Register as a Maid
              </h2>
              <p class="text-muted">Create your profile and start finding work opportunities</p>
            </div>

            <!-- Error Message -->
            <div *ngIf="errorMessage" class="alert alert-danger" role="alert">
              <i class="fa fa-exclamation-triangle me-2"></i>{{ errorMessage }}
            </div>

            <form [formGroup]="maidRegisterForm" (ngSubmit)="onSubmit()">
              <div class="row">
                <!-- Full Name -->
                <div class="col-md-6 mb-3">
                  <label for="fullName" class="form-label">Full Name <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-user"></i>
                    </span>
                    <input
                      type="text"
                      id="fullName"
                      formControlName="fullName"
                      class="form-control"
                      [class.is-invalid]="getFieldError('fullName')"
                      placeholder="Enter your full name">
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('fullName')">
                    {{ getFieldError('fullName') }}
                  </div>
                </div>

                <!-- Gender -->
                <div class="col-md-6 mb-3">
                  <label for="gender" class="form-label">Gender <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-venus-mars"></i>
                    </span>
                    <select
                      id="gender"
                      formControlName="gender"
                      class="form-select"
                      [class.is-invalid]="getFieldError('gender')">
                      <option value="">Select Gender</option>
                      <option value="female">Female</option>
                      <option value="male">Male</option>
                    </select>
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('gender')">
                    {{ getFieldError('gender') }}
                  </div>
                </div>
              </div>

              <div class="row">
                <!-- Nationality -->
                <div class="col-md-6 mb-3">
                  <label for="nationality" class="form-label">Nationality <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-globe"></i>
                    </span>
                    <input
                      type="text"
                      id="nationality"
                      formControlName="nationality"
                      class="form-control"
                      [class.is-invalid]="getFieldError('nationality')"
                      placeholder="Enter your nationality">
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('nationality')">
                    {{ getFieldError('nationality') }}
                  </div>
                </div>

                <!-- Emirate -->
                <div class="col-md-6 mb-3">
                  <label for="emirate" class="form-label">Emirate <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-map-marker"></i>
                    </span>
                    <select
                      id="emirate"
                      formControlName="emirate"
                      class="form-select"
                      [class.is-invalid]="getFieldError('emirate')">
                      <option value="">Select Emirate</option>
                      <option value="Abu Dhabi">Abu Dhabi</option>
                      <option value="Dubai">Dubai</option>
                      <option value="Sharjah">Sharjah</option>
                      <option value="Ajman">Ajman</option>
                      <option value="Umm Al Quwain">Umm Al Quwain</option>
                      <option value="Ras Al Khaimah">Ras Al Khaimah</option>
                      <option value="Fujairah">Fujairah</option>
                    </select>
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('emirate')">
                    {{ getFieldError('emirate') }}
                  </div>
                </div>
              </div>

              <div class="row">
                <!-- Visa Status -->
                <div class="col-md-6 mb-3">
                  <label for="visaStatus" class="form-label">Visa Status <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-id-card"></i>
                    </span>
                    <select
                      id="visaStatus"
                      formControlName="visaStatus"
                      class="form-select"
                      [class.is-invalid]="getFieldError('visaStatus')">
                      <option value="">Select Visa Status</option>
                      <option value="Own Visa">Own Visa</option>
                      <option value="Employer Visa">Employer Visa</option>
                      <option value="Visit Visa">Visit Visa</option>
                      <option value="No Visa">No Visa</option>
                    </select>
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('visaStatus')">
                    {{ getFieldError('visaStatus') }}
                  </div>
                </div>

                <!-- Visa Expiry Date -->
                <div class="col-md-6 mb-3">
                  <label for="visaExpiryDate" class="form-label">Visa Expiry Date <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-calendar"></i>
                    </span>
                    <input
                      type="date"
                      id="visaExpiryDate"
                      formControlName="visaExpiryDate"
                      class="form-control"
                      [class.is-invalid]="getFieldError('visaExpiryDate')">
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('visaExpiryDate')">
                    {{ getFieldError('visaExpiryDate') }}
                  </div>
                </div>
              </div>

              <div class="row">
                <!-- Mobile Number -->
                <div class="col-md-6 mb-3">
                  <label for="mobileNumber" class="form-label">Mobile Number <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text bg-light">+971</span>
                    <input
                      type="tel"
                      id="mobileNumber"
                      formControlName="mobileNumber"
                      class="form-control"
                      [class.is-invalid]="getFieldError('mobileNumber')"
                      placeholder="50 123 4567"
                      maxlength="9"
                      (input)="formatMobileNumber($event)">
                  </div>
                  <small class="text-muted">Enter 9 digits without country code</small>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('mobileNumber')">
                    {{ getFieldError('mobileNumber') }}
                  </div>
                </div>

                <!-- WhatsApp Number -->
                <div class="col-md-6 mb-3">
                  <label for="whatsappNumber" class="form-label">WhatsApp Number <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text bg-light">+971</span>
                    <select class="form-select" formControlName="whatsappEmirate" style="max-width: 140px;">
                      <option value="4">04 (Dubai)</option>
                      <option value="2">02 (Abu Dhabi)</option>
                      <option value="6">06 (Sharjah)</option>
                      <option value="3">03 (Ajman)</option>
                      <option value="9">09 (Ras Al Khaimah)</option>
                      <option value="7">07 (Fujairah)</option>
                    </select>
                    <input
                      type="tel"
                      id="whatsappNumber"
                      formControlName="whatsappNumber"
                      class="form-control"
                      [class.is-invalid]="getFieldError('whatsappNumber')"
                      placeholder="123 4567"
                      maxlength="7"
                      (input)="formatWhatsAppNumber($event)">
                  </div>
                  <small class="text-muted">Enter 7 digits</small>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('whatsappNumber')">
                    {{ getFieldError('whatsappNumber') }}
                  </div>
                </div>
              </div>

              <div class="row">
                <!-- Email Address -->
                <div class="col-md-6 mb-3">
                  <label for="email" class="form-label">Email Address <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-envelope"></i>
                    </span>
                    <input
                      type="email"
                      id="email"
                      formControlName="email"
                      class="form-control"
                      [class.is-invalid]="getFieldError('email')"
                      placeholder="your.email@example.com">
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('email')">
                    {{ getFieldError('email') }}
                  </div>
                </div>
              </div>

              <div class="row">
                <!-- Password -->
                <div class="col-md-6 mb-3">
                  <label for="password" class="form-label">Password <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-lock"></i>
                    </span>
                    <input
                      [type]="showPassword ? 'text' : 'password'"
                      id="password"
                      formControlName="password"
                      class="form-control"
                      [class.is-invalid]="getFieldError('password')"
                      placeholder="Create a password">
                    <button
                      type="button"
                      class="btn btn-outline-secondary"
                      (click)="togglePasswordVisibility()">
                      <i class="fa" [class.fa-eye]="!showPassword" [class.fa-eye-slash]="showPassword"></i>
                    </button>
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('password')">
                    {{ getFieldError('password') }}
                  </div>
                </div>

                <!-- Confirm Password -->
                <div class="col-md-6 mb-3">
                  <label for="confirmPassword" class="form-label">Confirm Password <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <i class="fa fa-lock"></i>
                    </span>
                    <input
                      [type]="showConfirmPassword ? 'text' : 'password'"
                      id="confirmPassword"
                      formControlName="confirmPassword"
                      class="form-control"
                      [class.is-invalid]="getFieldError('confirmPassword')"
                      placeholder="Confirm your password">
                    <button
                      type="button"
                      class="btn btn-outline-secondary"
                      (click)="toggleConfirmPasswordVisibility()">
                      <i class="fa" [class.fa-eye]="!showConfirmPassword" [class.fa-eye-slash]="showConfirmPassword"></i>
                    </button>
                  </div>
                  <div class="invalid-feedback d-block" *ngIf="getFieldError('confirmPassword')">
                    {{ getFieldError('confirmPassword') }}
                  </div>
                </div>
              </div>

              <!-- Terms and Conditions -->
              <div class="mb-4">
                <div class="form-check">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    id="agreeToTerms"
                    formControlName="agreeToTerms"
                    [class.is-invalid]="getFieldError('agreeToTerms')">
                  <label class="form-check-label" for="agreeToTerms">
                    I agree to the
                    <a href="#" class="text-decoration-none">Terms of Service</a>
                    and
                    <a href="#" class="text-decoration-none">Privacy Policy</a>
                  </label>
                </div>
                <div class="invalid-feedback d-block" *ngIf="getFieldError('agreeToTerms')">
                  {{ getFieldError('agreeToTerms') }}
                </div>
              </div>

              <!-- Submit Button -->
              <button
                type="submit"
                class="btn btn-primary w-100 py-2 mb-3"
                [disabled]="isLoading">
                <span *ngIf="isLoading" class="spinner-border spinner-border-sm me-2"></span>
                {{ isLoading ? 'Registering...' : 'Register as Maid' }}
              </button>
            </form>

            <!-- Divider -->
            <div class="text-center my-4">
              <span class="text-muted">Already have a maid account?</span>
            </div>

            <!-- Login Link -->
            <div class="text-center mb-3">
              <a routerLink="/maid-login" class="btn btn-outline-primary w-100">
                <i class="fa fa-sign-in me-2"></i>Sign In Instead
              </a>
            </div>

            <!-- Switch to Customer Registration -->
            <div class="text-center">
              <a routerLink="/register" class="text-decoration-none text-muted small">
                <i class="fa fa-users me-1"></i>Are you a Customer? Register here
              </a>
            </div>
          </div>
        </div>

        <!-- Additional Info -->
        <div class="text-center mt-4">
          <p class="text-muted small">
            By registering, you agree to our
            <a href="#" class="text-decoration-none">Terms of Service</a>
            and
            <a href="#" class="text-decoration-none">Privacy Policy</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

// nextjs/src/app/maid-register/page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { EMIRATES, NATIONALITIES, VISA_STATUS } from "@/lib/constants";

const schema = z
  .object({
    fullName: z.string().min(2, "Full name is required"),
    gender: z.enum(["female", "male"], { message: "Select gender" }),
    nationality: z.string().min(2, "Nationality is required"),
    emirate: z.string().min(2, "Emirate is required"),
    visaStatus: z.string().min(2, "Visa status is required"),
    visaExpiryDate: z.string().min(1, "Visa expiry date is required"),
    mobileNumber: z.string().regex(/^\d{9}$/, "Mobile number must be 9 digits"),
    whatsappNumber: z.string().regex(/^\d{9}$/, "WhatsApp number must be 9 digits"),
    email: z.string().email("Please enter a valid email address"),
    password: z.string().min(6, "Password must be at least 6 characters"),
    confirmPassword: z.string().min(6, "Confirm password is required"),
  })
  .refine((v) => v.password === v.confirmPassword, {
    message: "Passwords do not match",
    path: ["confirmPassword"],
  });

type FormValues = z.infer<typeof schema>;

export default function MaidRegisterPage() {
  const router = useRouter();
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({ resolver: zodResolver(schema) });

  const onSubmit = async () => {
    await new Promise((r) => setTimeout(r, 900));
    router.push("/maid-login");
  };

  return (
    <section className="mx-auto mt-10 max-w-4xl px-4 sm:px-6">
      <div className="card">
        <h1 className="text-2xl font-bold text-slate-900">Register as Maid</h1>
        <p className="mt-1 text-sm text-slate-600">Create your maid profile with complete information.</p>

        <form className="mt-6 grid gap-4 md:grid-cols-2" onSubmit={handleSubmit(onSubmit)}>
          <Input label="Full Name" error={errors.fullName?.message}>
            <input className="field" {...register("fullName")} />
          </Input>
          <Input label="Gender" error={errors.gender?.message}>
            <select className="field" {...register("gender")}>
              <option value="">Select Gender</option>
              <option value="female">Female</option>
              <option value="male">Male</option>
            </select>
          </Input>
          <Input label="Nationality" error={errors.nationality?.message}>
            <select className="field" {...register("nationality")}>
              <option value="">Select Nationality</option>
              {NATIONALITIES.map((n) => (
                <option key={n} value={n}>
                  {n}
                </option>
              ))}
            </select>
          </Input>
          <Input label="Emirate" error={errors.emirate?.message}>
            <select className="field" {...register("emirate")}>
              <option value="">Select Emirate</option>
              {EMIRATES.map((e) => (
                <option key={e} value={e}>
                  {e}
                </option>
              ))}
            </select>
          </Input>
          <Input label="Visa Status" error={errors.visaStatus?.message}>
            <select className="field" {...register("visaStatus")}>
              <option value="">Select Visa Status</option>
              {VISA_STATUS.map((v) => (
                <option key={v} value={v}>
                  {v}
                </option>
              ))}
            </select>
          </Input>
          <Input label="Visa Expiry Date" error={errors.visaExpiryDate?.message}>
            <input className="field" type="date" {...register("visaExpiryDate")} />
          </Input>
          <Input label="Mobile Number" error={errors.mobileNumber?.message} hint="Prefix +971">
            <input className="field" placeholder="50 123 4567" {...register("mobileNumber")} />
          </Input>
          <Input label="WhatsApp Number" error={errors.whatsappNumber?.message} hint="Prefix +971">
            <input className="field" placeholder="50 123 4567" {...register("whatsappNumber")} />
          </Input>
          <Input label="Email Address" error={errors.email?.message}>
            <input className="field" type="email" {...register("email")} />
          </Input>
          <Input label="Password" error={errors.password?.message}>
            <input className="field" type="password" {...register("password")} />
          </Input>
          <Input label="Confirm Password" error={errors.confirmPassword?.message}>
            <input className="field" type="password" {...register("confirmPassword")} />
          </Input>

          <div className="md:col-span-2">
            <button className="btn btn-primary w-full" disabled={isSubmitting} type="submit">
              {isSubmitting ? "Registering..." : "Register as Maid"}
            </button>
          </div>
        </form>

        <div className="mt-4 text-center text-sm">
          <Link href="/maid-login" className="text-brand hover:underline">
            Already have maid account? Sign in
          </Link>
        </div>
      </div>
    </section>
  );
}

function Input({
  label,
  children,
  error,
  hint,
}: {
  label: string;
  children: React.ReactNode;
  error?: string;
  hint?: string;
}) {
  return (
    <div>
      <label className="mb-1 block text-sm font-semibold">{label}</label>
      {children}
      {hint ? <p className="mt-1 text-xs text-slate-500">{hint}</p> : null}
      {error ? <p className="mt-1 text-xs text-red-600">{error}</p> : null}
    </div>
  );
}
